services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-backend-1
    command: sleep infinity
    ports:
      - "8000:8000"
    environment:
      PROJECT_NAME: BackendBase
      ENVIRONMENT: dev
      PORT: 8000
    volumes:
      - .:/app