services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: ["sh", "-c", "uvicorn src.app:app --host 0.0.0.0 --port ${PORT:-8000} --reload"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app