services:
  # Único servicio: nuestra aplicación Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-backend-1
    # Mantenemos el contenedor corriendo para poder entrar a su shell
    command: sleep infinity
    ports:
      - "8000:8000"
    volumes:
      # Montamos el código local para ver cambios en tiempo real
      - .:/app
    environment:
      # La URL ahora apunta a un archivo SQLite que se creará dentro de /app
      PROJECT_NAME: BackendBase
      ENVIRONMENT: dev