name: Build and push Docker image to ECR (triggered after tests)

on:
  workflow_run:
    workflows:
      - "Code Quality Checks - Tests"
    types:
      - completed

jobs:
  deploy-after-tests:
    # solo continuar si el workflow anterior terminó con éxito y en la rama main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names "backend-base" --region "us-east-1" || \
            aws ecr create-repository --repository-name "backend-base" --region "us-east-1"

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-qemu-action@v2

      - name: Build and push image to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend-base:latest
          platforms: linux/amd64

      - name: Output image uri
        run: echo "Image pushed: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend-base:latest"

      # Opcional: forzar App Runner deployment si no usás "Automatic deployments"
      - name: Trigger App Runner deployment (optional)
        if: ${{ secrets.APP_RUNNER_SERVICE_ARN != '' }}
        run: |
          aws apprunner start-deployment --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" --region "us-east-1"