name: Deploy to Neon (manual)

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment label (e.g. production)'
        required: false
        default: 'production'

jobs:
  migrate:
    name: Run Alembic migrations on Neon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run migrations
        run: make alembic-upgrade
        env:
          ENVIRONMENT: ${{ github.event.inputs.env }}
          PROJECT_NAME: BackendBase
          DB_URL_SYNC: ${{ secrets.NEON_DB_SYNC }}
