name: Deploy to Render (manual trigger after tests)

on:
  workflow_dispatch: {}

jobs:
  deploy-render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          set -euo pipefail
          RESP=$(curl -s -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json")
          echo "Trigger response: $RESP"
          DEPLOY_ID=$(echo "$RESP" | jq -r '.id')
          if [ -z "${DEPLOY_ID}" ] || [ "${DEPLOY_ID}" = "null" ]; then
            echo "❌ Failed to trigger deploy"; exit 1
          fi
          echo "✅ Deploy Triggered (ID: ${DEPLOY_ID})"

      - name: Health Check Public URL
        uses: jtalk/url-health-check-action@v4
        if: success()
        with:
          url: ${{ secrets.RENDER_URL }}
          max-attempts: 12
          retry-delay: 20s

      - name: Summary
        run: echo "✅ Render CI/CD Completed. Service is Live and Responding."
